### ISSUE TITLE
storage group_name nginx 未替换

### ISSUE THREAD

**Issue by xulu** [WhitePi/fastdfs-nginx-docker#2]
storage中的nginx配置只支持
`location ~/group[0-9]/`
所以指定其他名称不会生效
我觉得应该在storage.sh中加入
`sed -i "s|group[0-9]|${GROUP_NAME}|g" /usr/local/nginx/conf/nginx.conf`

**Comment by WhitePi** [comment]
非常感谢宝贵的建议；
已加入对用户定义的group_name转发；
保留原先group[0-9]+的正则匹配，这个在多个storage的情况下比较方便（当然，group定义名称需满足group+数字的方式）
另外修复了storage原先mod_fastdfs.conf配置没有更改问题和docker compose启动错误问题；

**Comment by xulu** [comment]
非常感谢，学习了
